import Button from '../../../../../common/button/index'
export const data = [
  {
    key: "1",
    number: 101,
    name: "Акмаль",
    plus: '800',
    enumerationplus: '1500',
    dateofdeparture: '01.04.2023',
    otherexpenses: '',
    minus: '500.000',
    comment: 'Asus',
    smenaclose: "",
    // render: () => <a>Delete</a>,
  },
    {
    key: "2",
    number: 102,
    name: "Акмаль",
    plus: '',
    enumerationplus: '',
    dateofdeparture: '01.04.2023',
    otherexpenses: '',
    minus: '500.000',
    comment: 'Olx',
    smenaclose: "",
  },
   {
    key: "3",
    number: 103,
    name: "Акмаль",
    plus: '',
    enumerationplus: '1100',
    dateofdeparture: '01.04.2023',
    otherexpenses: '',
    minus: '7.500.000',
    comment: 'Apple',
    smenaclose: "",
  },
  {
    key: "4",
    number: 104,
    name: "Акмаль",
    plus: '1100',
    enumerationplus: '',
    dateofdeparture: '01.04.2023',
    otherexpenses: '',
    minus: '',
    comment: '',
    smenaclose: "",
  },
    {
    key: "5",
    number: 105,
    name: "Акмаль",
    plus: '800',
    enumerationplus: '1500',
    dateofdeparture: '01.04.2023',
    otherexpenses: '',
    minus: '500.000',
    comment: 'Asus',
    smenaclose: "",
  },
    {
    key: "6",
    number: 106,
    name: "Акмаль",
    plus: '',
    enumerationplus: '',
    dateofdeparture: '01.04.2023',
    otherexpenses: '',
    minus: '500.000',
    comment: 'Olx',
    smenaclose: "",
  },
   {
    key: "7",
    number: 107,
    name: "Акмаль",
    plus: '',
    enumerationplus: '1100',
    dateofdeparture: '01.04.2023',
    otherexpenses: '',
    minus: '7.500.000',
    comment: 'Apple',
    smenaclose: "",
  },
  {
    key: "8",
    number: 108,
    name: "Акмаль",
    plus: '1100',
    enumerationplus: '',
    dateofdeparture: '01.04.2023',
    otherexpenses: '',
    minus: '',
    comment: '',
    smenaclose: "",
  },
  {
    key: "9",
    number: 109,
    name: "Акмаль",
    plus: '',
    enumerationplus: '1100',
    dateofdeparture: '01.04.2023',
    otherexpenses: '',
    minus: '7.500.000',
    comment: 'Apple',
    smenaclose: "",
  },
  {
    key: "10",
    number: 110,
    name: "Акмаль",
    plus: '1100',
    enumerationplus: '',
    dateofdeparture: '01.04.2023',
    otherexpenses: '',
    minus: '',
    comment: '',
    smenaclose: "",
  },
];
